version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-producto-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_user
      MYSQL_USER: javauser
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - producto-network

volumes:
  mysql_data:

networks:
  producto-network:
    driver: bridge